global using Microsoft.OpenApi.Any;
global using Microsoft.OpenApi.Models;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using Swashbuckle.AspNetCore.Annotations;
global using Serilog;
global using CommonService;
global using EventService.Models;
global using EventService.Services;
global using EventService.Infrastructure;